let myName= "Sobit";
let age= 20;
let isStudent=true;
console.log(myName);
console.log(age);
console.log(isStudent);
const college="Tu";
console.log(college);
let myNamee="Hari";
console.log(typeof myNamee);
let future;
let name= "Ram";
let colleg="eic";
let semester=4;
console.log("My name is" +name +" and i study at" +colleg);
console.log(`My name is ${name} and i study at ${colleg}, semester ${semester}`);
let a=10;
let b=3;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a %b);
console.log(a**b);
console.log(5 =="5");
console.log(5 === "5");
console.log(5 ==5);
console.log(5 ===5);